server:
  port: 9001
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DB_CONNECTION_STRING:jdbc:mysql://localhost:3306/orders}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:codaglobal}
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
  flyway:
    enabled: false
    validate-on-migrate: true
